hood/complaints/urls.py
from django.conf.urls import patterns, url
from .views import ComplaintCreateView, ComplaintListView, ThankYouComplaintView

urlpatterns = patterns('',
    url(r'^buildings/(?P<building_slug>[-\w]+)/complaints/$', ComplaintListView.as_view(), name='complaints'),
    url(r'^buildings/(?P<building_slug>[-\w]+)/complaints/create/$', ComplaintCreateView.as_view(), name='complaints_create'),
    url(r'^gracias/$', ThankYouComplaintView.as_view(), name='thanks'),
)

hood/hood/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('accounts.urls')),
    url(r'^', include('administrators.urls')),
    url(r'^', include('budgets.urls')),
    url(r'^', include('buildings.urls')),
    url(r'^', include('complaints.urls')),
    url(r'^', include('emails.urls')),
    url(r'^', include('meetns.urls')),
    url(r'^', include('movements.urls')),
    url(r'^', include('properties.urls')),
    url(r'^', include('wallet.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('userena.urls')),
    url(r'^media/(?P<path>.*)$','django.views.static.serve',
        {'document_root':settings.MEDIA_ROOT,}
    )
]

hood/complaints/models.py
from django.db import models
from buildings.models import Building

class Complaint(models.Model):
	building = models.ForeignKey(Building)
	sender_name = models.CharField(max_length=100)
	sender_email = models.EmailField(max_length=254)
	message = models.TextField(max_length=2000)

	def __str__(self):
		return self.sender_name

hood/complaints/forms.py
from django import forms
from .models import Complaint

class ComplaintCreateForm(forms.ModelForm):
	class Meta:
		model = Complaint
		fields = ['sender_name', 'sender_email', 'message']

hood/complaints/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.views.generic import CreateView, TemplateView, ListView
from buildings.models import Building
from .models import Complaint
from .forms import ComplaintCreateForm

class ComplaintCreateView(CreateView):
	model = Complaint
	form_class = ComplaintCreateForm
	success_url = reverse_lazy("thanks")
	template_name = "complaints/create_complaint.html"

	def form_valid(self, form):
		building_slug = self.kwargs["building_slug"]
		building_obj = Building.objects.get(slug__iexact=building_slug)
		form.instance.building = building_obj
		return super(ComplaintCreateView, self).form_valid(form)

	def get_context_data(self, *args, **kwargs):
		context = super(ComplaintCreateView, self).get_context_data(**kwargs)
		building_slug = self.kwargs["building_slug"]
		building_obj = Building.objects.get(slug__iexact=building_slug)
		context["building"] = building_obj
		return context


class ThankYouComplaintView(TemplateView):
	template_name = "complaints/thankyou.html"

class ComplaintListView(ListView):
	template_name = "complaints/complaint_list.html"
	model = Complaint
	context_object_name = "complaints"

	def get_context_data(self, *args, **kwargs):
		context = super(ComplaintListView, self).get_context_data(**kwargs)
		building_slug = self.kwargs["building_slug"]
		building_obj = Building.objects.get(slug__iexact=building_slug)
		context["building"] = building_obj
		return context

	def get_queryset(self, **kwargs):
		building_slug = self.kwargs['building_slug']
		queryset = Complaint.objects.filter(building__slug=building_slug)
		return queryset

hood/templates/complaints/complaint_list.html
{% extends "base.html" %}
{% block leftbar %}
            <div class="left side-menu">
                <div class="sidebar-inner slimscrollleft">
                    <div class="user-details">
                        <div class="user-info">
                            <div>
                                <span aria-expanded="false">
                                    Edificio {{building.name}}
                                </span>
                             </div>
                              {% if userprofile.is_administrator %}
                        <p class="text-muted m-0">Administrador</p>
                              {% elif userprofile.is_watchman %}
                              <p class="text-muted m-0">Celador</p>
                              {% else %}
                              {% endif %}
                    </div>
                </div>
                <div id="sidebar-menu">
                    <ul>
                              {% if perms.properties %}
                              <li>
                                   <a href="{% url "properties" building.slug %}" class="waves-effect">
                                        <i class="md md-home"></i>
                                        <span>Copropiedad</span>
                                   </a>
                              </li>
                              {% else %}
                              {% endif %}
                              {% if perms.wallet %}
                        <li>
                            <a href="{% url "wallet" building.slug %}" class="waves-effect">
                                <i class="md md-account-balance-wallet"></i>
                                <span>Cartera</span>
                                <span class="pull-right">
                                    <i class="md md-add"></i>
                                </span>
                            </a>
                        </li>
                              {% else %}
                              {% endif %}
                              {% if perms.budgets %}
                        <li>
                            <a href="{% url "budgets" building.slug %}" class="waves-effect">
                                <i class="md md-attach-money"></i>
                                <span>Presupuesto</span>
                            </a>
                        </li>
                              {% else %}
                              {% endif %}
                              {% if perms.emails %}
                        <li>
                            <a href="{% url "emails" building.slug %}" class="waves-effect">
                                <i class="md md-email"></i>
                                <span>Emails</span>
                            </a>
                        </li>
                              {% else %}
                              {% endif %}
                              {% if perms.complaints %}
                        <li>
                            <a href="{% url "complaints" building.slug %}" class="waves-effect">
                                <i class="md  md-announcement"></i> 
                                <span>Quejas</span> 
                                <span class="pull-right">
                                <i class="md md-add"></i>
                                </span>
                            </a>    
                         </li>
                              {% else %}
                              {% endif %}
                        
                         {% if perms.meetns %}
                         <li>
                            <a href="{% url "meetings" building.slug %}" class="waves-effect">
                                <i class="md md-invert-colors-on"></i>
                                <span>Asambleas/Reuniones</span>
                                <span class="pull-right">
                                    <i class="md md-add"></i>
                                </span>
                            </a>
                         </li>
                         {% else %}
                         {% endif %}
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="clearfix"></div>
               </div>
          </div>
          {% endblock %}
                {% block content %}
    				<div class="content-page">
    						<div class="content">
    							<div class="container">
    								<div class="row">
    								<div class="col-sm-12">
    									<h4 class="pull-left page-title">Mensajes</h4>
    								</div>
    								</div>
    								<div class="panel">
    								<div class="panel-body">
    								<div class="row">
    								</div>
    								</div>
    								<table class="table table-bordered table-striped" id="datatable-editable">
    								<thead>
    								<tr>
    									<th>Nombre del Remitente</th>
    									<th>Email del Remitente</th>
    									<th>Mensaje</th>
                                        <th>Acciones</th>
    								</tr>
    								</thead>
    								<tbody>
    								{% for complaint in complaints %}
    								<tr class="gradeX">
    								<td>{{complaint.sender_name}}</td>
    								<td>{{complaint.sender_email}}</td>
    								<td>{{complaint.message}}</td>
    								<td class="actions">
                                    <a href="#" class="on-default">
                                        <i class="fa fa-eye"></i>
                                    </a>
    								<a href="#" class="on-default">
    									<i class="fa fa-pencil"></i>
    								</a> 
    								</td>
    								</tr>
    								{% endfor %}
    							</tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            {% endblock %}

hood/templates/complaints/create_complaint.html
{% extends "base.html" %}
{% block content %}
{% block leftbar %}{% endblock %}
<div class="content-page-buildings">
	<div class="content">
		<div class="container">
			<div class="row">
				<div class="col-sm-12">
					<h4 class="pull-left page-title">Edificio {{building.name}}</h4>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-12">
					<div class="panel panel-default">
						<div class="panel-heading">
							<h3 class="panel-title">Enviar una queja</h3>
						</div>
						<div class="panel-body">
						<form class="form-horizontal" role="form" method="POST">
						{% csrf_token %}
							<div class="form-group">
								<label class="col-md-2 control-label">Tu nombre</label>
								<div class="col-md-6">
									<input id="id_sender_name" maxlength="100" type="text" class="form-control" name="sender_name" placeholder="Nombre">
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label" for="example-email">Tu Email</label>
								<div class="col-md-6">
									<input id="id_sender_email" maxlength="254" name="sender_email" type="email" class="form-control" placeholder="Email">
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label">Mensaje</label>
								<div class="col-md-6">
									<textarea cols="40" id="id_message" maxlength="2000" name="message" rows="10" class="form-control"></textarea>
								</div>
							</div>
							<div class="form-group m-b-0">
    							<div class="col-sm-offset-3 col-sm-9">
    								<button type="submit" class="btn btn-info waves-effect waves-light">Enviar Queja</button>
    							</div>
    						</div>
						</form>
					</div>
				</div>
			</div>
		</div>

	{% endblock %}

hood/templates/complaints/thankyou.html
{% extends "base.html" %}
  {% block content %}
  {% block leftbar %}{% endblock %}
  <section class="home bg-dark" id="home">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 text-center">
          <div class="home-wrapper">
            <h1 class="home-text">
              <span class="rotate">Gracias</span>
            </h1>
            <p class="m-t-30">Hemos recibido tu queja, el administrador del edificio se encargará de darle el debido seguimiento</p>
            <div class="row m-t-40">
              <div class="col-sm-12 lj-countdown">
                <div class="row">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  {% endblock %}
  {% block custom-js %}
  <script>var resizefunc = [];</script>
  <script src="assets/js/moltran.min.js"></script>
  <script src="assets/vendor/countdown/dest/jquery.countdown.min.js"></script>
  <script src="assets/plugins/simple-text-rotator/jquery.simple-text-rotator.min.js"></script>
  <script type="text/javascript">$(document).ready(function (){

        // Countdown
        // To change date, simply edit: var endDate = "June 26, 2015 20:39:00";
        $(function() {
          var endDate = "January 17, 2016 20:39:00";
          $('.lj-countdown .row').countdown({
            date: endDate,
            render: function(data) {
              $(this.el).html('<div><div><span>' + (parseInt(this.leadingZeros(data.years, 2)*365) + parseInt(this.leadingZeros(data.days, 2))) + '</span><span>days</span></div><div><span>' + this.leadingZeros(data.hours, 2) + '</span><span>hours</span></div></div><div class="lj-countdown-ms"><div><span>' + this.leadingZeros(data.min, 2) + '</span><span>minutes</span></div><div><span>' + this.leadingZeros(data.sec, 2) + '</span><span>seconds</span></div></div>');
            }
          });
        });
      });
      $(document).ready(function(){
        $(".home-text .rotate").textrotator({
              animation: "fade",
              speed: 2000
          });
      });</script>
  {% endblock %}