hood/accounts/urls.py
from django.conf.urls import patterns, url
from userena.views import signin
from .views import signup
from .forms import SignupFormExtra
urlpatterns = patterns('',
    url(r'^login/$', signin, {"template_name":"accounts/login.html",}, name="login"),
    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login', name="logout"),
    url(r'^signup/$', signup, {"template_name":"accounts/register.html", 'signup_form': SignupFormExtra}, name="signup"),
)

hood/hood/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('accounts.urls')),
    url(r'^', include('administrators.urls')),
    url(r'^', include('budgets.urls')),
    url(r'^', include('buildings.urls')),
    url(r'^', include('complaints.urls')),
    url(r'^', include('emails.urls')),
    url(r'^', include('meetns.urls')),
    url(r'^', include('movements.urls')),
    url(r'^', include('properties.urls')),
    url(r'^', include('wallet.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('userena.urls')),
    url(r'^media/(?P<path>.*)$','django.views.static.serve',
        {'document_root':settings.MEDIA_ROOT,}
    )
]

hood/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from userena.models import UserenaBaseProfile

PROFILE_TYPES = (
    (u'USER', 'User'),
    (u'ADMN', 'Admin'),
    (u'WTMN', 'Watchman'),
)

class UserProfile(UserenaBaseProfile):
    user = models.OneToOneField(User, related_name="user_profile")
    address = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)
    name = models.CharField(max_length=100, blank=True)
    phone_number = models.CharField(max_length=100, blank=True)
    user_type = models.CharField(choices=PROFILE_TYPES, max_length=16)
	#some common fields here, which are shared among both administrator and individual profiles

    def is_administrator(self):
        if self.user_type == "ADMN":
            return True
        else:
            return False

    def is_watchman(self):
        if self.user_type == "WTMN":
            return True
        else:
            return False

class AdministratorProfile(models.Model):
    profile = models.ForeignKey(UserProfile)
    #administrator special fields here

    class Meta:
        db_table = 'administrator_profile'

#class IndividualUser(models.Model):
#    profile = models.ForeignKey(UserProfile)
    #Individual user fields here
#
#   class Meta:
#        db_table = 'individual_user'

hood/budgets/models.py
from django.db import models
from buildings.models import Building
from datetime import datetime, timedelta

class Provider(models.Model):
	address = models.CharField(max_length=100)
	bank_account_number = models.CharField(max_length=100, blank=True)
	email = models.EmailField(max_length=254)
	name =  models.CharField(max_length=100)
	phone_number = models.CharField(max_length=100)
	service =  models.CharField(max_length=100)

	def __str__(self):
		return self.name

FRECUENCY_CHOICES = (
	(7, 'Semanal'),
	(15, 'Quincenal'),
	(30, 'Mensual'),
	(91, 'Trimestral'),
	(182, 'Semestral'),
	(365, 'Anual'),
)

class Budget(models.Model):
	building = models.ForeignKey(Building)
	total_price = models.IntegerField(null=True, blank=True)
	year = models.IntegerField()

	def __str__(self):
		return self.building.name

class BudgetItem(models.Model):
	budget = models.ForeignKey(Budget)
	concept = models.CharField(max_length=250)
	monthly_quantity = models.CharField(max_length=250, blank=True)
	annual_quantity = models.CharField(max_length=250, blank=True)

	def __str__(self):
		return self.concept


	#def calculate_payments(self, pk, period, budget_life_starting, budget_life_ending):
	#	period = timedelta(days=period)
	#	budget = Budget.objects.get(pk=pk)
	#	life_starting = str(budget_life_starting.month) + '/' + str(budget_life_starting.day) + '/' + str(budget_life_starting.year)
	#	life_starting = datetime.strptime(life_starting, '%m/%d/%Y')
	#	life_ending = str(budget_life_ending.month) + '/' + str(budget_life_ending.day) + '/' + str(budget_life_ending.year)
	#	life_ending = datetime.strptime(life_ending, '%m/%d/%Y')
	#	date_of_payment = life_starting + period

	#	while True:
	#		if date_of_payment < life_ending:
	#			BudgetPayment.objects.create(date_of_payment=date_of_payment, budget=budget)
	#			date_of_payment = date_of_payment + period
	#			continue
	#		else:
	#			break

	#def calculate_total_price(self, period, budget_life_starting, budget_life_ending, unit_price):
	#	period = timedelta(days=period)
	#	life_starting = str(budget_life_starting.month) + '/' + str(budget_life_starting.day) + '/' + str(budget_life_starting.year)
	#	life_starting = datetime.strptime(life_starting, '%m/%d/%Y')
	#	life_ending = str(budget_life_ending.month) + '/' + str(budget_life_ending.day) + '/' + str(budget_life_ending.year)
	#	life_ending = datetime.strptime(life_ending, '%m/%d/%Y')
	#	date_of_payment = life_starting + period
	#	payments_counter = 0

	#	while True:
	#		if date_of_payment < life_ending:
	#			payments_counter += 1
	#			date_of_payment = date_of_payment + period
	#			continue
	#		else:
	#			break
	#	total_price = abs(int(payments_counter)) * abs(int(unit_price))
	#	return total_price

	#def save(self, *args, **kwargs):
	#	obj_created = False
	#	if not self.pk:
	#		self.total_price = self.calculate_total_price(self.frecuency, self.budget_life_starting, self.budget_life_ending, self.unit_price)
	#		super(Budget, self).save(*args, **kwargs)
	#		obj_created = True
	#	if obj_created:
	#		self.calculate_payments(self.pk, self.frecuency, self.budget_life_starting, self.budget_life_ending)


class BudgetPayment(models.Model):
	date_of_payment = models.DateField()
	budget = models.ForeignKey(Budget)
	paid = models.BooleanField(default=False)

	def __str__(self):
		return self.budget.item

hood/accounts/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from userena.forms import SignupForm
from userena.utils import get_user_profile

from .models import AdministratorProfile
from django.contrib.auth.models import Group

PROFILE_TYPES = (
    (u'USER', 'User'),
    (u'ADMN', 'Admin'),
    (u'WTMN', 'Watchman'),
)

class SignupFormExtra(SignupForm):
    name = forms.CharField(label=_(u'Name'),max_length=30,required=False)
    last_name = forms.CharField(label=_(u'Last Name'),max_length=30,required=False)
    address = forms.CharField(label=_(u'Address'),max_length=30,required=False)
    phone_number = forms.CharField(label=_(u'Phone Number'),max_length=30,required=False)
    user_type = forms.ChoiceField(choices=PROFILE_TYPES, widget=forms.HiddenInput())

    def save(self):
        """
        Override the save method to save the first and last name to the user
        field.

        """
        # Original save method returns the user
        user = super(SignupFormExtra, self).save()

        # Get the profile, the `save` method above creates a profile for each
        # user because it calls the manager method `create_user`.
        # See: https://github.com/bread-and-pepper/django-userena/blob/master/userena/managers.py#L65
        user_profile = get_user_profile(user=user)

        # Be sure that you have validated these fields with `clean_` methods.
        # Garbage in, garbage out.
        user_profile.name = self.cleaned_data['name']
        user_profile.last_name = self.cleaned_data['last_name']
        user_profile.address = self.cleaned_data['address']
        user_profile.phone_number = self.cleaned_data['phone_number']
        user_profile.user_type = self.cleaned_data['user_type']

        if self.cleaned_data['user_type'] == "ADMN" and user:
            try:
                group = Group.objects.get(name="Administrator")
                user.groups.add(group)
            except:
                pass
        elif self.cleaned_data['user_type'] == "WTMN" and user:
            try:
                group = Group.objects.get(name="Watchman")
                user.groups.add(group)
            except:
                pass
        else:
            pass

        user.save()
        user_profile.save()
        return user

hood/accounts/views.py
import logging
import warnings
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout, REDIRECT_FIELD_NAME
from django.views.generic import TemplateView
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.conf import settings
from django.utils.translation import ugettext as _
from django.http import Http404, HttpResponseRedirect
from userena.forms import SignupForm
from userena.models import UserenaSignup
from userena.decorators import secure_required
from userena.utils import (signin_redirect, get_profile_model, get_user_model,
                           get_user_profile)
from userena import signals as userena_signals
from userena import settings as userena_settings
from guardian.decorators import permission_required_or_403

try:
    mixpanel = settings.MIXPANEL
except:
    mixpanel = False

logger = logging.getLogger(__name__)

class ExtraContextTemplateView(TemplateView):
    """ Add extra context to a simple template view """
    extra_context = None

    def get_context_data(self, *args, **kwargs):
        context = super(ExtraContextTemplateView, self).get_context_data(*args, **kwargs)
        if self.extra_context:
            context.update(self.extra_context)
        return context

    # this view is used in POST requests, e.g. signup when the form is not valid
    post = TemplateView.get

@secure_required
def signup(request, signup_form=SignupForm,
           template_name='userena/signup_form.html', success_url=None,
           extra_context=None):
    """
    Signup of an account.

    Signup requiring a username, email and password. After signup a user gets
    an email with an activation link used to activate their account. After
    successful signup redirects to ``success_url``.

    :param signup_form:
        Form that will be used to sign a user. Defaults to userena's
        :class:`SignupForm`.

    :param template_name:
        String containing the template name that will be used to display the
        signup form. Defaults to ``userena/signup_form.html``.

    :param success_url:
        String containing the URI which should be redirected to after a
        successful signup. If not supplied will redirect to
        ``userena_signup_complete`` view.

    :param extra_context:
        Dictionary containing variables which are added to the template
        context. Defaults to a dictionary with a ``form`` key containing the
        ``signup_form``.

    **Context**

    ``form``
        Form supplied by ``signup_form``.

    """
    # If signup is disabled, return 403
    if userena_settings.USERENA_DISABLE_SIGNUP:
        raise PermissionDenied

    # If no usernames are wanted and the default form is used, fallback to the
    # default form that doesn't display to enter the username.
    if userena_settings.USERENA_WITHOUT_USERNAMES and (signup_form == SignupForm):
        signup_form = SignupFormOnlyEmail

    form = signup_form(initial={'user_type': 'ADMN'})

    if request.method == 'POST':
        form = signup_form(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()

            # Send the signup complete signal
            userena_signals.signup_complete.send(sender=None,
                                                 user=user)


            if success_url: redirect_to = success_url
            else: redirect_to = reverse('userena_signup_complete',
                                        kwargs={'username': user.username})

            # A new signed user should logout the old one.
            if request.user.is_authenticated():
                logout(request)

            if (userena_settings.USERENA_SIGNIN_AFTER_SIGNUP and
                not userena_settings.USERENA_ACTIVATION_REQUIRED):
                user = authenticate(identification=user.email, check_password=False)
                login(request, user)

            try:
                new_user_profile = get_user_profile(user)
                if new_user_profile.user_type == "ADMN" and mixpanel:
                    mixpanel.people_set(user.id, {
                        '$first_name'    : new_user_profile.name,
                        '$last_name'     : new_user_profile.last_name,
                        '$email'         : new_user_profile.user.email,
                        '$phone'         : new_user_profile.phone_number
                    })
                    mixpanel.track(user.id, 'Registro de usuario completado')
            except Exception as error:
                logger.error("No se pudo agregar el perfil del administrador a Mixpanel: {0}".format(error), exc_info=True, extra={
                                'request': request,
                })
            return redirect(redirect_to)

    if not extra_context: extra_context = dict()
    extra_context['form'] = form
    return ExtraContextTemplateView.as_view(template_name=template_name,
                                            extra_context=extra_context)(request)
@secure_required
def activate(request, activation_key,
             template_name='userena/activate_fail.html',
             retry_template_name='userena/activate_retry.html',
             success_url=None, extra_context=None):
    """
    Activate a user with an activation key.

    The key is a SHA1 string. When the SHA1 is found with an
    :class:`UserenaSignup`, the :class:`User` of that account will be
    activated.  After a successful activation the view will redirect to
    ``success_url``.  If the SHA1 is not found, the user will be shown the
    ``template_name`` template displaying a fail message.
    If the SHA1 is found but expired, ``retry_template_name`` is used instead,
    so the user can proceed to :func:`activate_retry` to get a new activation key.

    :param activation_key:
        String of a SHA1 string of 40 characters long. A SHA1 is always 160bit
        long, with 4 bits per character this makes it --160/4-- 40 characters
        long.

    :param template_name:
        String containing the template name that is used when the
        ``activation_key`` is invalid and the activation fails. Defaults to
        ``userena/activate_fail.html``.

    :param retry_template_name:
        String containing the template name that is used when the
        ``activation_key`` is expired. Defaults to
        ``userena/activate_retry.html``.

    :param success_url:
        String containing the URL where the user should be redirected to after
        a successful activation. Will replace ``%(username)s`` with string
        formatting if supplied. If ``success_url`` is left empty, will direct
        to ``userena_profile_detail`` view.

    :param extra_context:
        Dictionary containing variables which could be added to the template
        context. Default to an empty dictionary.

    """
    try:
        if (not UserenaSignup.objects.check_expired_activation(activation_key)
            or not userena_settings.USERENA_ACTIVATION_RETRY):
            user = UserenaSignup.objects.activate_user(activation_key)
            if user:
                # Sign the user in.
                auth_user = authenticate(identification=user.email,
                                         check_password=False)
                login(request, auth_user)

                if userena_settings.USERENA_USE_MESSAGES:
                    messages.success(request, _('Your account has been activated and you have been signed in.'),
                                     fail_silently=True)

                if success_url: redirect_to = success_url % {'username': user.username }
                else: redirect_to = reverse('userena_profile_detail',
                                            kwargs={'username': user.username})
                return redirect(redirect_to)
            else:
                if not extra_context: extra_context = dict()
                return ExtraContextTemplateView.as_view(template_name=template_name,
                                                        extra_context=extra_context)(
                                        request)
        else:
            if not extra_context: extra_context = dict()
            extra_context['activation_key'] = activation_key
            return ExtraContextTemplateView.as_view(template_name=retry_template_name,
                                                extra_context=extra_context)(request)
    except UserenaSignup.DoesNotExist:
        if not extra_context: extra_context = dict()
        return ExtraContextTemplateView.as_view(template_name=template_name,
                                                extra_context=extra_context)(request)

hood/templates/accounts/login.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">
		<meta name="author" content="Coderthemes">
		<link rel="shortcut icon" href="assets/images/favicon_1.ico">
		<title>Moltran - Responsive Admin Dashboard Template</title>
		<link href="{% static "css/styles.css" %}" rel="stylesheet" type="text/css"><!--[if lt IE 9]><script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script><![endif]-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
      </head>
      <body>
      	<div class="wrapper-page">
      		<div class="panel panel-color panel-primary panel-pages">
      			<div class="panel-heading bg-img">
      				<div class="bg-overlay">      					
      				</div>
      				<h3 class="text-center m-t-10 text-white">
      					<strong>Inicia Sesión</strong>
      				</h3>
      			</div>
      			<div class="panel-body">
      				<form class="form-horizontal m-t-20" method="POST" action="">
      					{% csrf_token %}
      					<div class="form-group">
      						<div class="col-xs-12">
      							<input class="form-control input-lg required" id="id_identification" type="text" name="identification" placeholder="Email o nombre de usuario">
      						</div>
      					</div>
      					<div class="form-group">
      						<div class="col-xs-12">
      							<input class="form-control input-lg required" id="id_password" name="password" type="password" placeholder="Contraseña">
      						</div>
      					</div>
      					<div class="form-group">
      						<div class="col-xs-12">
      							<div class="checkbox checkbox-primary">
      							<input id="id_remember_me" name="remember_me" type="checkbox" />
      							<label for="id_remember_me">Recordarme</label>
      						</div>
      					</div>

      				</div>
      				<div class="form-group text-center m-t-40">
      					<div class="col-xs-12">
      						<button class="btn btn-primary btn-lg w-lg waves-effect waves-light" type="submit">Log In</button>
      					</div>
      				</div>
      				<div class="form-group m-t-30">
      					<div class="col-sm-7">
      						<a href="recoverpw.html">
      							<i class="fa fa-lock m-r-5"></i> ¿Olvidaste tu contraseña?
      						</a>
      					</div>
      					<div class="col-sm-5 text-right">
      						<a href="{% url "signup" %}">Registarte</a>
      					</div>
      				</div>
      			</form>
      		</div>
      	</div>
      </div>
      <script>var resizefunc = [];</script><script src="{% static "js/hood.js" %}"></script></body></html>

hood/templates/accounts/register.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">
		<meta name="author" content="Coderthemes">
		<link rel="shortcut icon" href="assets/images/favicon_1.ico">
		<title>Moltran - Responsive Admin Dashboard Template</title>
		<link href="{% static "css/styles.css" %}" rel="stylesheet" type="text/css"><!--[if lt IE 9]><script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script><![endif]-->
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
	</head>
	<body>
		<div class="wrapper-page">
			<div class="panel panel-color panel-primary panel-pages">
				<div class="panel-heading bg-img">
					<div class="bg-overlay"></div>
					<h3 class="text-center m-t-10 text-white">Registrate</h3>
				</div>
				<div class="panel-body">
					<form class="form-horizontal m-t-20" name="user_form" method="POST" action="">
					{% csrf_token %}
    					<div class="form-group">
    						<div class="col-xs-12">
    							{{form.username.errors}}
    							<input class="form-control input-lg required" id="id_username"name="username" type="text" placeholder="Username"/>
    						</div>
    					</div>
						<div class="form-group">
							<div class="col-xs-12">
    							{{form.email.errors}}
								<input class="form-control input-lg required" id="id_email" name="email" type="text" placeholder="Email" />
							</div>
    					</div>
    					<div class="form-group">
    						<div class="col-xs-12">
    							{{form.name.errors}}
    							<input class="form-control input-lg required" id="id_name" name="name" type="text" maxlength="30" name="name" placeholder="Tu nombre"/>
    						</div>
    					</div>
    					<div class="form-group">
    						<div class="col-xs-12">
    							{{form.last_name.errors}}
    							<input class="form-control input-lg required" id="id_last_name" name="last_name" type="text" maxlength="30" placeholder="Tu apellido"/>
    						</div>
    					</div>
    					<div class="form-group">
    						<div class="col-xs-12">
    							{{form.address.errors}}
    							<input class="form-control input-lg required" id="id_address" type="text" maxlength="30" name="address" placeholder="Tu direccion"/>
    						</div>
    					</div>
    					<div class="form-group">
    						<div class="col-xs-12">
    							{{form.phone_number.errors}}
    							<input class="form-control input-lg required" id="id_phone_number" name="phone_number" type="text" maxlength="30" placeholder="Tu telefono"/>
    						</div>
    					</div>
						<div class="form-group">
							<div class="col-xs-12">
								{{form.password1.errors}}
								<input class="form-control input-lg required" id="id_password1" name="password1" type="password" placeholder="Contraseña"/>
							</div>
						</div>
						<div class="form-group">
							<div class="col-xs-12">
								{{form.password2.errors}}
								<input class="form-control input-lg required" id="id_password2" name="password2" type="password" placeholder="Confirma tu contraseña"/>
							</div>
						</div>
						<div class="form-group">
							<div class="col-xs-12">
								{{form.user_type.errors}}
								<input class="form-control input-lg required" id="id_user_type" name="user_type" type="hidden" value="ADMN" />
							</div>
						</div>
						<div class="form-group text-center m-t-40">
							<div class="col-xs-12">
								<button class="btn btn-primary waves-effect waves-light btn-lg w-lg" type="submit">Registrarme
								</button>
							</div>
						</div>
						<div class="form-group m-t-30">
							<div class="col-sm-12 text-center">
								<a href="{% url "login" %}">¿Ya tienes una cuenta?</a>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
		<script>var resizefunc = [];</script>
        <script src="js/hood.js"></script></body></html>