hood/hood/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('accounts.urls')),
    url(r'^', include('administrators.urls')),
    url(r'^', include('budgets.urls')),
    url(r'^', include('buildings.urls')),
    url(r'^', include('complaints.urls')),
    url(r'^', include('emails.urls')),
    url(r'^', include('meetns.urls')),
    url(r'^', include('movements.urls')),
    url(r'^', include('properties.urls')),
    url(r'^', include('wallet.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('userena.urls')),
    url(r'^media/(?P<path>.*)$','django.views.static.serve',
        {'document_root':settings.MEDIA_ROOT,}
    )
]

hood/wallet/urls.py
from django.conf.urls import patterns, url
from .views import (AdministrationFeeListView, AdministrationFeePaymentListView, 
	AdministrationFeePaymentsByMonth, next_by_month, mark_as_paid, mark_as_paid_inline, 
	mark_as_paid_inline_by_month, create_wallet, get_payment, get_payments_ajax)

urlpatterns = patterns('',
    url(r'^buildings/(?P<building_slug>[-\w]+)/wallet/$', AdministrationFeeListView.as_view(), name='wallet'),
    url(r'^buildings/(?P<building_slug>[-\w]+)/wallet/monthly$', AdministrationFeePaymentsByMonth.as_view(), name='wallet_by_month'),
    url(r'^buildings/(?P<building_slug>[-\w]+)/wallet/create$', create_wallet, name='create_wallet'),
    url(r'^buildings/(?P<building_slug>[-\w]+)/wallet/(?P<apartment_pk>[-\w]+)/payments/$', AdministrationFeePaymentListView.as_view(), name='adminfee_payments'),
    url(r'^wallet/(?P<payment_id>[0-9]+)/paid/$', mark_as_paid, name="payment_paid"),
    url(r'^inlinewallet/(?P<payment_id>[0-9]+)/paid/$', mark_as_paid_inline, name="payment_paid_inline"),
    url(r'^walletbymonth/(?P<payment_id>[0-9]+)/paid/$', mark_as_paid_inline_by_month, name="wallet_by_month_paid"),
    url(r'^walletbymonth/(?P<payment_id>[0-9]+)/$', get_payment, name="get_payment"),
    url(r'^walletbymonth/(?P<payment_id>[0-9]+)/next/$', next_by_month, name="wallet_by_month_next"),
    url(r'^api/ajax_search/$', get_payments_ajax, name="autocomplete_payments_search"),
)

hood/wallet/models.py
import datetime
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone
from properties.models import Apartment
from datetime import datetime, timedelta
from buildings.models import Building
from movements.models import CashFlow
from .tasks import register_fees

class BuildingWallet(models.Model):
	building = models.OneToOneField(Building)
	day_of_recurrent_payment = models.IntegerField()
	has_discount_early_payment = models.BooleanField(default=False)
	discount_early_payment_amount = models.CharField(max_length=50, blank=True)
	cashflow_for_wallet_payments = models.ForeignKey(CashFlow, null=True, on_delete=models.SET_NULL)
	timestamp = models.DateField(auto_now_add=True)
	
	def __str__(self):
		return self.building.name

	def save(self, *args, **kwargs):
		if not self.pk:
			super(BuildingWallet, self).save(*args, **kwargs)
			register_fees.delay(self.building.id, self.day_of_recurrent_payment, self.timestamp.isoformat())
		else:
			super(BuildingWallet, self).save(*args, **kwargs)

#class ApartmentBalance(models.Model):
#	apartment = models.ForeignKey(Apartment, null=True, on_delete=models.SET_NULL)
#	advance = models.BigIntegerField(default=0)
#	debt = models.BigIntegerField(default=0)

#	def receipt():
#
#
#PEDIR DATE OF RECURRENT PAYMENT
#CALCULAR GENERACIÓN DE RECIBO EL 25 DE CADA MES

class AdministrationFee(models.Model):
	apartment = models.OneToOneField(Apartment)
	date_of_recurrent_payment = models.DateField()
	fee_life_starting = models.DateField()
	fee_life_ending = models.DateField()
	fee_value = models.IntegerField()

	def __str__(self):
		return self.apartment.name

#	def calculate_payments(self, pk, date_of_recurrent_payment, fee_life_starting, fee_life_ending):
#		one_month = timedelta(days=30)
#		administration_fee = AdministrationFee.objects.get(pk=pk)
#		date_of_recurrent_payment = str(date_of_recurrent_payment.month) + '/' + str(date_of_recurrent_payment.day) + '/' + str(date_of_recurrent_payment.year)
#		date_of_recurrent_payment = datetime.strptime(date_of_recurrent_payment, '%m/%d/%Y')
#		fee_life_starting = str(fee_life_starting.month) + '/' + str(fee_life_starting.day) + '/' + str(fee_life_starting.year)
#		fee_life_starting = datetime.strptime(fee_life_starting, '%m/%d/%Y')
#		fee_life_ending = str(fee_life_ending.month) + '/' + str(fee_life_ending.day) + '/' + str(fee_life_ending.year)
#		fee_life_ending = datetime.strptime(fee_life_ending, '%m/%d/%Y')
#		date_of_payment = date_of_recurrent_payment + one_month
		
#		while 1:
#			if date_of_payment < fee_life_ending:
#				Payment.objects.create(date_of_payment=date_of_payment, administration_fee=administration_fee)
#				date_of_payment = date_of_payment + one_month
#				continue
#			else:
#				break

#	def save(self, *args, **kwargs):
#		obj_created = False
#		if not self.pk:
#			super(AdministrationFee, self).save(*args, **kwargs)
#			obj_created = True
#		if obj_created:
#			self.calculate_payments(self.pk, self.date_of_recurrent_payment, self.fee_life_starting, self.fee_life_ending)


class Payment(models.Model):
	apartment = models.ForeignKey(Apartment, null=True, on_delete=models.SET_NULL)
	date_of_payment = models.DateField()
	paid = models.BooleanField(default=False)
	payment_record_date = models.DateField(null=True, blank=True)
	fee_value = models.CharField(max_length=50, blank=True)

	def get_next_payment(self):
		next_payment = Payment.get_next_by_date_of_payment(self)
		next_payment = next_payment.apartment
		return next_payment

	def __str__(self):
		return self.fee_value

hood/wallet/forms.py
from django import forms
from django.forms import ModelForm
from movements.models import CashFlow
from .models import BuildingWallet, Payment

class CreateWalletForm(ModelForm):
	has_discount_early_payment = forms.TypedChoiceField(coerce=lambda x: x == 'True', choices=((True, 'Si'), (False, 'No')), widget=forms.RadioSelect, required=False)

	class Meta:
		model = BuildingWallet
		fields = ["day_of_recurrent_payment", "has_discount_early_payment", "discount_early_payment_amount", "cashflow_for_wallet_payments"]

	def __init__(self, building, *args, **kwargs):
		super(CreateWalletForm, self).__init__(*args, **kwargs)
		self.fields['cashflow_for_wallet_payments'].queryset = CashFlow.objects.filter(building=building)

hood/wallet/views.py
import json
import datetime
import logging
from django.conf import settings
from django.shortcuts import render, get_object_or_404, render_to_response
from django.views.generic import View, ListView, CreateView, DetailView, FormView
from django.views.generic.detail import SingleObjectMixin
from django.http import HttpResponse, HttpResponseForbidden
from django.utils import timezone
from django.template import RequestContext
from django.shortcuts import redirect
from django.core.urlresolvers import reverse
from properties.models import Apartment
from buildings.models import Building
from meetns.utils import render_to_json_response
from movements.models import Income
from movements.views import add_income
from .models import AdministrationFee, Payment, BuildingWallet
from .forms import CreateWalletForm
from .tasks import format_price

try:
	mixpanel = settings.MIXPANEL
except:
	mixpanel = False

logger = logging.getLogger(__name__)

def format_price(price):
		price = price.replace(",","")
		price = price.replace(".","")
		price = int(price)

		return price

def create_wallet(request, *args, **kwargs):
	building_slug = kwargs["building_slug"]
	building = get_object_or_404(Building, slug__iexact=building_slug)
	if request.method == "POST":
		print (request.POST)
		form = CreateWalletForm(building, request.POST)
		if form.is_valid():
			wallet = form.save(commit=False)
			wallet.building = building
			wallet.save()

			try:
				if mixpanel:
					mixpanel.track(request.user.id, "Registro de cartera completado")
			except Exception as error:
				logger.error("No se pudo trackear el registro de cartera en Mixpanel: {0}".format(error), exc_info=True, extra={
                    'request': request,
                })

			success_url = reverse("properties", kwargs={'building_slug': building_slug})
			return redirect(success_url)
		else:
			print ("TIENE ERRORES MENOR")
			return render_to_response("wallet/create_wallet.html", RequestContext(request, {"form": form, "building": building}))
	else:
		form = CreateWalletForm(building)
		return render_to_response("wallet/create_wallet.html", RequestContext(request, {"form": form, "building": building}))
	
class AdministrationFeeListView(ListView):
	model = AdministrationFee
	apartment_model = Apartment
	template_name = "wallet/administrationfee_list.html"

	def get_context_data(self, *args, **kwargs):
		context = super(AdministrationFeeListView, self).get_context_data(**kwargs)
		building_slug = self.kwargs['building_slug']
		building_object = Building.objects.get(slug__iexact=building_slug)
		apartments_in_building = self.apartment_model.objects.filter(building=building_object)
		context['building'] = building_object
		context['apartments'] = apartments_in_building
		return context


#be careful at this point. The latest payment MUST be the latest payment, U can not register
#a payment of august and then one of april, cuz the latest will be april and everyting
#will go to shit
#class AdministrationFeeListView(ListView):
#	model = AdministrationFee
#	apartment_model = Apartment
#	template_name = "wallet/administrationfee_list.html"

#	def get_context_data(self, *args, **kwargs):
#		context = super(AdministrationFeeListView, self).get_context_data(**kwargs)
#		building_slug = self.kwargs['building_slug']
#		building_object = Building.objects.get(slug__iexact=building_slug)
#		apartments_in_building = self.apartment_model.objects.filter(building=building_object)
#		context['building'] = building_object
#		apartments_with_delay = []
#		apartments_without_delay = []
#		apartments_without_adminfee = []
#		today = datetime.today()
#		today = str(today.month) + '/' + str(today.day) + '/' + str(today.year)
#		today = datetime.strptime(today, '%m/%d/%Y')

#		for apto in apartments_in_building:
#			try:
#				if apto.administrationfee.payment_set.filter(date_of_payment__lt=today, paid=False):
#					payments_not_paid = apto.administrationfee.payment_set.filter(date_of_payment__lt=today, paid=False)
#					for payment in payments_not_paid:
#						payment_date = payment.date_of_payment
#						payment_date = str(payment_date.month) + '/' + str(payment_date.day) + '/' + str(payment_date.year)
#						payment_date = datetime.strptime(payment_date, '%m/%d/%Y')
#						days_between = abs((today - payment_date).days)
#						if days_between > 30:
#							delay_days = days_between - 30
#							apartments_with_delay.append(apto)
#							break
#				else:
#					apartments_without_delay.append(apto)
#			except self.model.DoesNotExist:
#				apartments_without_adminfee.append(apto)

#		context['apartments_with_delay'] = apartments_with_delay
#		context['apartments_without_delay'] = apartments_without_delay
#		context['apartments_without_adminfee'] = apartments_without_adminfee
#		return context

def get_payments_ajax(request, *args, **kwargs):
	if request.is_ajax():
		q = request.GET.get('term', '')
		today = timezone.now()
		payments = Payment.objects.filter(apartment__name__icontains=q, date_of_payment__month=today.month)
		results =[]
		for payment in payments:
			payment_json = {}
			payment_json["id"] = payment.id
			payment_json["label"] = "Apartamento: {0}".format(payment.apartment.name)
			payment_json["value"] = "Apartamento: {0}".format(payment.apartment.name)
			results.append(payment_json)
		data = json.dumps(results)
	else:
		return HttpResponseForbidden()
	mimetype = 'application/json'
	return HttpResponse(data, mimetype)

class AdministrationFeePaymentsByMonth(DetailView):
	model = Payment
	template_name = "wallet/payments_by_month.html"
	context_object_name = "payment"

	def get_object(self, **kwargs):
		building_slug = self.kwargs['building_slug']
		today = timezone.now()
		try:
			obj = Payment.objects.filter(
				apartment__building__slug=building_slug, 
				date_of_payment__month=today.month, 
				date_of_payment__year=today.year, 
				paid=False).order_by("id").first()
			print ("GOT obj")
		except Exception as lol:
			print (lol)
			obj = None
		return obj

	def get_context_data(self, *args, **kwargs):
		context = super(AdministrationFeePaymentsByMonth, self).get_context_data(*args, **kwargs)
		building_slug = self.kwargs["building_slug"]
		building_object = Building.objects.get(slug__iexact=building_slug)
		context["building"] = building_object
		wallet = BuildingWallet.objects.get(building=building_object)
		context["discount_early_payment"] = format_price(wallet.discount_early_payment_amount)
		today = timezone.now()
		context["current_time"] = today
		return context

class AdministrationFeePaymentListView(ListView):
	model = Payment
	apartment_model = Apartment
	template_name = "wallet/payments_list.html"

	def get_object(self, *args, **kwargs):
		building_slug = self.kwargs['building_slug']
		apartment_pk = self.kwargs['apartment_pk']
		building_object = Building.objects.get(slug__iexact=building_slug)
		obj = self.apartment_model.objects.get(pk=apartment_pk, building=building_object)
		return obj

	def get_context_data(self, *args, **kwargs):
		context = super(AdministrationFeePaymentListView, self).get_context_data(*args, **kwargs)
		apto_obj = self.get_object()
		payments = apto_obj.payment_set.all().order_by("date_of_payment")
		building_slug = self.kwargs['building_slug']
		building_object = Building.objects.get(slug__iexact=building_slug)
		context['building'] = building_object
		context['apartment'] = apto_obj
		context['payments'] = payments
		return context

def mark_as_paid(request, payment_id):
#	if request.method == "POST":
#		post_payment_record_date = request.POST.get("payment_record_date")
#		post_fee_value = request.POST.get("fee_value")
	payment = get_object_or_404(Payment, id=payment_id)
	payment.paid = True
	payment.save()
	payment_record_date = payment.payment_record_date.strftime("%b. %d, %Y")
	concept_of_income = "Cuota de Admon. Apto: {0}".format(payment.apartment.name)
	context = {"paid": payment.paid, "payment_record_date":payment_record_date}
	add_income_result = add_income(
		building=payment.apartment.building, 
		price=payment.fee_value, 
		concept=concept_of_income, 
		date=payment.payment_record_date)
	if add_income_result == True:
		pass
	else:
		context["error"] = True
	return render_to_json_response(context)

def mark_as_paid_inline(request, payment_id):
	if request.method == "POST":
		post_payment_record_date = request.POST.get("payment_record_date")
		post_fee_value = request.POST.get("fee_value")
		date_format = datetime.datetime.strptime(post_payment_record_date, "%m/%d/%Y")
		valid_payment_record_date = datetime.date(year=date_format.year, month=date_format.month, day=date_format.day)
		valid_fee_value = format_price(post_fee_value)

		payment = get_object_or_404(Payment, id=payment_id)
		payment.payment_record_date = valid_payment_record_date
		payment.fee_value = valid_fee_value
		payment.paid = True
		payment.save()
	elif request.method == "GET":
		return HttpResponseForbidden()
	apartment_object = payment.apartment
	context = {}
	try:
		print ("GOT INTRO TRY")
		new_next_payment = apartment_object.payment_set.filter(paid=False).order_by("date_of_payment").first()
		new_next_payment_id = new_next_payment.id
		new_next_payment_date = new_next_payment.date_of_payment.strftime("%b. %d, %Y")
		context["new_next_payment_id"] = new_next_payment_id
		context["new_next_payment_date"] = new_next_payment_date
		context["new_next_payment_value"] = new_next_payment.fee_value
	except Exception as lol:
		print ("GOT INTO EXCEPCITON")
		print (lol)
		context["next_payment_error"] = True
	concept_of_income = "Cuota de Admon. Apto: {0}".format(payment.apartment.name)
	add_income_result = add_income(
		building=payment.apartment.building, 
		price=payment.fee_value, 
		concept=concept_of_income, 
		date=payment.payment_record_date)
	if add_income_result == True:
		pass
	else:
		context["error"] = True
	return render_to_json_response(context)

def mark_as_paid_inline_by_month(request, payment_id):
	if request.method == "POST":
		try:

hood/templates/wallet/create_wallet.html
{% extends "base.html" %}
{% load i18n %}
{% load static from staticfiles %}
{% load extra_tags %}
{% block custom-css %}
    <link href="{% static "css/stepsForm.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "css/responsive.css" %}" rel="stylesheet" type="text/css">
    <script src="{% static "js/modernizr.min.js" %}" type="text/javascript"></script>
    <script src="{% static "js/jquery-2.1.1.min.js" %}"></script>
{% endblock %}
{% block leftbar %}
{% endblock %}
{% block content %}
	<div class="content-page-buildings">
		<div class="content">
			<div class="container">
				<div class="panel">
					<div class="row">
						<div class="col-md-12">
							<div class="panel panel-default">
								<div class="panel-heading">
									<h3 class="panel-title">Configuración del Módulo de Cartera</h3>
								</div>
								<div class="panel-body">
								<div>
									<div class="text-center" style="margin-bottom: 2em;">
										<h3>¡Excelente! Sólo nos falta un pequeño dato para comenzar</h3>	
									</div>
                  <div class="row">
                    <div class="col-md-6 col-md-offset-3 col-sm-12 col-xs-12">
                      <div class="createWForm">
              					<form method="POST" lpformnum="1">
                          <input type="hidden" name="csrfmiddlewaretoken" value="csNgDED775N8q6OtAekkY46xG9a9AAWv">
                          <div class="row">
                            <div class="col-md-6 col-md-offset-3 form-group">
                              Dia de pago recurrente:
                              <input id="id_day_of_recurrent_payment" class="form-control formFlow" name="day_of_recurrent_payment" type="number">
                            </div>
                          </div>
                          <div class="row">
                            <div class="col-md-6 col-md-offset-3 form-group">
                              <div class=" checkbox-primary">
                                <label style="text-align:center">Aplicar descuento por pago oportuno  <span id="id_has_discount_early_payment"></span></label>
                                <div class="input-group switchBtn" style="margin-top: 1em;">
                                    <input id="id_has_discount_early_payment_0" class="switchBtn-input" name="has_discount_early_payment" type="radio" value="True" />
                                    <label for="id_has_discount_early_payment_0" class="switchBtn-label switchBtn-label-off">Si</label>
                                    <input id="id_has_discount_early_payment_1" class="switchBtn-input" name="has_discount_early_payment" type="radio" value="False" style="margin-left: 20px;" checked />
                                    <label for="id_has_discount_early_payment_1" class="switchBtn-label switchBtn-label-on">No</label>
                                    <span class="switchBtn-selection"></span>
                                </div>
                              </div>
                            </div>
                          </div>

                              <!--<ul id="id_has_discount_early_payment">
                              <li><label for="id_has_discount_early_payment_0"><input id="id_has_discount_early_payment_0" name="has_discount_early_payment" type="radio" value="True"> Si</label></li>
                          <li><label for="id_has_discount_early_payment_1"><input id="id_has_discount_early_payment_1" name="has_discount_early_payment" type="radio" value="False"> No</label></li></ul>-->
                          <div class="row" id="EarlyValue" style="display:none">
                            <div class="col-md-6 col-md-offset-3 form-group">
                              Valor descuento por pronto pago:
                              <input id="id_discount_early_payment_amount" class="form-control formFlow" maxlength="50" name="discount_early_payment_amount" type="text">
                            </div>
                          </div>
                          <div class="row">
                            <div class="col-md-6 col-md-offset-3 form-group">
                              Caja para pago de cartera:
                              <select id="id_cashflow_for_wallet_payments" class="form-control formFlow" name="cashflow_for_wallet_payments">
                                <option value="" selected="selected">---------</option>
                                <option value="3">Caja de Cuenta de Ahorros</option>
                                <option value="2">Caja de Cuenta Corriente</option>
                                <option value="1">Caja Menor</option>
                              </select>
                            </div>
                          </div>
                          <div class="row">
                            <div class="col-md-6 col-md-offset-3 form-group text-center">
                              <button type="submit" class="btn btn-primary" style="margin-top: 2em;">¡Hecho!</button>
                            </div>
                          </div>
                        </form>
                      </div>
                    </div>
                  </div>
                            <!--
                  					<div class="col-sm-3 todo-inputbar form-group text-center" style="float: none; margin: 0 auto;">
                    					<span style="font-size: 16px;">¿Qué día del mes deben haberte pagado las cuotas de administración?</span>
                    					<div class="input-group" style="margin-top: 2em;">
                      						<span class="input-group-addon" id="basic-addon1">&nbsp;&nbsp;<i class="icon form fa-calendar"></i></span>
                      						<input id="id_building" name="building" type="hidden" value="{{building.id}}">
                      						<input id="id_day_of_recurrent_payment" name="day_of_recurrent_payment" type="number" min="1" max="31" class="form-control" style="font-size: 18px;"/>
                    					</div>
                    				</div>
                    				<div class="col-sm-3 todo-inputbar form-group text-center" style="float: none; margin: 0 auto;">
                    					<span style="font-size: 16px; display: inline-block; margin-top: 2em;">¿Haces Descuento por pago oportuno?</span>
                    					<div class="input-group switchBtn" style="margin-top: 1em;">
                      						<input id="id_has_discount_early_payment_0" class="switchBtn-input" name="has_discount_early_payment" type="radio" value="True" />
                      						<label for="id_has_discount_early_payment_0" class="switchBtn-label switchBtn-label-off">Si</label>
                      						<input id="id_has_discount_early_payment_1" class="switchBtn-input" name="has_discount_early_payment" type="radio" value="False" style="margin-left: 20px;" checked />
                      						<label for="id_has_discount_early_payment_1" class="switchBtn-label switchBtn-label-on">No</label>
                      						<span class="switchBtn-selection"></span>
                    					</div>
                    					<div class="input-group" style="margin-top: 2em;display:none;">
                      						<span class="input-group-addon" id="basic-addon1">&nbsp;&nbsp;&nbsp;<i class="icon form fa-dollar"></i></span>
                      						<input id="id_discount_early_payment_amount" name="discount_early_payment_amount" type="text" class="form-control" style="font-size: 18px;" placeholder="Valor del descuento" required="True"/>
                    					</div>
                    				</div>
                    				<div class="col-sm-3 todo-inputbar form-group text-center" style="float: none; margin: 0 auto;">
                                        <span style="font-size: 16px; display: inline-block; margin-top: 2em;">¿A qué fuente quieres agregar los pagos de administracion?</span>
                                        <div class="input-group" style="margin-top: 2em;">

                      						<select id="id_cashflow_for_wallet_payments" name="cashflow_for_wallet_payments" class="form-control">
                                                    {% for value, key in form.fields.cashflow_for_wallet_payments.choices %}
                                                        <option value="{{value}}" {% if form.cashflow_for_wallet_payments.value == value %} selected{% endif %}>{{key}}</option>

                                                    {% endfor %}
                                            </select>
                    					</div>
                                    </div>
                            -->
                				</div>
							</div>
						</div>
					</div>
					<!-- end: page -->
				</div><!-- end Panel -->
			</div><!-- container -->
		</div><!-- content -->
{% endblock %}
{% block custom-js %}
	<footer class="footer text-right">2015 © Regente.</footer></div>

	<script type="text/javascript">
		$(document).ready(function(){
			$('.input-group input:radio').click(function(){
				//console.log($(this).val());
				if($(this).val() == 'True')
				{
					$(this).closest('.input-group').next('.input-group').fadeIn();
				}
				else
				{
					$(this).closest('.input-group').next('.input-group').fadeOut();
				}

			});

      $('.switchBtn-input').click(function(){
          var discount = $('.switchBtn-input:checked').val();

          if(discount == 'True')
          {
            $('#EarlyValue').fadeIn(800);
          }
          else
          {
            $('#EarlyValue').fadeOut();
          }
      });
		});
	</script>
{% endblock %}