hood/hood/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('accounts.urls')),
    url(r'^', include('administrators.urls')),
    url(r'^', include('budgets.urls')),
    url(r'^', include('buildings.urls')),
    url(r'^', include('complaints.urls')),
    url(r'^', include('emails.urls')),
    url(r'^', include('meetns.urls')),
    url(r'^', include('movements.urls')),
    url(r'^', include('properties.urls')),
    url(r'^', include('wallet.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('userena.urls')),
    url(r'^media/(?P<path>.*)$','django.views.static.serve',
        {'document_root':settings.MEDIA_ROOT,}
    )
]

hood/properties/urls.py
from django.conf.urls import patterns, url
from .views import ApartmentsListView, ApartmentDetailView, ApartmentUpdateView, OwnerUpdateView, InhabitantUpdateView, VisitCreateView, ApartmentImport, ApartmentProcessImport, ApartmentExport, OwnerImport, OwnerExport, OwnerProcessImport, InhabitantImport, InhabitantExport, InhabitantProcessImport
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
    url(r'^buildings/(?P<building_slug>[-\w]+)/properties/$', ApartmentsListView.as_view(), name='properties'),
    url(r'^buildings/(?P<building_slug>[-\w]+)/properties/import$', login_required(ApartmentImport.as_view()), name='properties_import'),
    url(r'^buildings/(?P<building_slug>[-\w]+)/properties/(?P<apartment_pk>[-\w]+)$', ApartmentDetailView.as_view(), name='property_detail'),
    url(r'^buildings/(?P<building_slug>[-\w]+)/properties/(?P<apartment_pk>[-\w]+)/edit/$', ApartmentUpdateView.as_view(), name='property_edit'),
    url(r'^buildings/(?P<building_slug>[-\w]+)/properties/(?P<apartment_pk>[-\w]+)/edit/owner/$', OwnerUpdateView.as_view(), name='property_owner_edit'),
    url(r'^buildings/(?P<building_slug>[-\w]+)/properties/(?P<apartment_pk>[-\w]+)/edit/inhabitant/(?P<inhabitant_pk>[0-9a-f])/$', InhabitantUpdateView.as_view(), name='property_inhabitant_edit'),
    url(r'^buildings/(?P<building_slug>[-\w]+)/properties/(?P<apartment_pk>[-\w]+)/visit/create$', VisitCreateView.as_view(), name='visit_create'),
    url(r'^buildings/(?P<building_slug>[-\w]+)/properties/export/$', ApartmentExport.as_view(), name='properties_export'),
    url(r'^buildings/(?P<building_slug>[-\w]+)/properties/import/$', login_required(ApartmentImport.as_view()), name='data_import'),
    url(r'^(?P<building_slug>[-\w]+)/process_import$', login_required(ApartmentProcessImport.as_view()), name='process_import'),
    url(r'^buildings/(?P<building_slug>[-\w]+)/owners/import/$', login_required(OwnerImport.as_view()), name='owner_import'),
    url(r'^buildings/(?P<building_slug>[-\w]+)/owners/export/$', login_required(OwnerExport.as_view()), name='owner_export'),
    url(r'^buildings/(?P<building_slug>[-\w]+)/inhabitants/export/$', login_required(InhabitantExport.as_view()), name='inhabitant_export'),
    url(r'^(?P<building_slug>[-\w]+)/owners/process_import$', login_required(OwnerProcessImport.as_view()), name='owner_process_import'),
    url(r'^buildings/(?P<building_slug>[-\w]+)/inhabitants/import/$', login_required(InhabitantImport.as_view()), name='inhabitant_import'),
    url(r'^(?P<building_slug>[-\w]+)/inhabitants/process_import$', login_required(InhabitantProcessImport.as_view()), name='inhabitant_process_import'),
)

hood/properties/models.py
from django.db import models
from django.template import defaultfilters
from import_export import resources
from buildings.models import Building

class Apartment(models.Model):
	building = models.ForeignKey(Building)
	area = models.IntegerField(help_text="Digite el area numericamente en m2", blank=True)
	registration_tag = models.CharField(max_length=100, blank=True)
	name = models.CharField(max_length=100)
	parking_number = models.CharField(max_length=100, blank=True)
	coefficient = models.DecimalField(max_digits=4, decimal_places=2)
	slug = models.SlugField(max_length=500)

	def save(self, *args, **kwargs):
		self.slug = defaultfilters.slugify(self.name)
		super(Apartment, self).save(*args, **kwargs)

	def get_owner(self):
		try:
			owner = self.owner_set.all()[0]
		except:
			owner = None
		return owner

	def get_latest_payment_registered(self):
		try:
			latest_payment = self.payment_set.filter(paid=True).order_by("date_of_payment").last()
			latest_payment_value = latest_payment.payment_record_date
		except Exception as lol:
			print (lol)
			latest_payment_value = None
		return latest_payment_value

	def __str__(self):
		return self.name

	def get_next_payment(self):
		try:
			next_payment = self.payment_set.filter(paid=False).order_by("date_of_payment").first()
		except Exception as lol:
			print (lol)
			next_payment = None
		return next_payment

class Owner(models.Model):
	apartments = models.ManyToManyField(Apartment)
	address = models.CharField(max_length=100)
	email = models.EmailField(max_length=254)
	last_name = models.CharField(max_length=100)
	name = models.CharField(max_length=100)
	phone_number = models.CharField(max_length=100)
	identification = models.CharField(max_length=100)
	has_pet = models.BooleanField(default=False)
	is_inhabitant = models.BooleanField(default=False)

	def __str__(self):
		return self.name + " " + self.last_name

class Inhabitant(models.Model):
	apartments = models.ManyToManyField(Apartment)
	email = models.EmailField(max_length=254)
	last_name = models.CharField(max_length=50)
	name = models.CharField(max_length=100)
	phone_number = models.CharField(max_length=100)
	
	def __str__(self):
		return self.name

class Visit(models.Model):
	visitor_name = models.CharField(max_length=100)
	visitor_lastname = models.CharField(max_length=100)
	visitor_identity = models.CharField(max_length=100)
	visit_timestamp = models.DateTimeField(auto_now_add=True)
	apartment = models.ForeignKey(Apartment)

	def __str__(self):
		return self.visitor_name

class AdministrativeCouncil(models.Model):
	building = models.ForeignKey(Building)
	members = models.ManyToManyField(Owner)

class ApartmentResource(resources.ModelResource):
    class Meta:
        model = Apartment

hood/properties/forms.py
from django import forms
from .models import Apartment

class ApartmentUpdateForm(forms.ModelForm):
	class Meta:
		model = Apartment
		fields = ['name', 'registration_tag', 'area', 'parking_number']

hood/properties/views.py
import csv
import logging
import os
import tempfile
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView, UpdateView, CreateView, View
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.contrib.auth.decorators import permission_required
from django.utils.decorators import method_decorator
from django.utils.encoding import force_text
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.conf import settings
from django.template.response import TemplateResponse
from django.http import HttpResponse
from import_export.forms import ImportForm
from import_export.forms import ConfirmImportForm
from import_export.formats import base_formats
from import_export.resources import modelresource_factory
from import_export import resources
from userena.utils import get_user_profile
from buildings.models import Building
from .decorators import verify_data
from .models import Apartment, Owner, Inhabitant, Visit, ApartmentResource
from .forms import ApartmentUpdateForm

try:
    mixpanel = settings.MIXPANEL
except:
    mixpanel = False

logger = logging.getLogger(__name__)

class ApartmentsListView(ListView):
	template_name = "properties/apartments.html"
	model = Apartment
	context_object_name = "apartments"

	@method_decorator(verify_data)
	def dispatch(self, *args, **kwargs):
		return super(ApartmentsListView, self).dispatch(*args, **kwargs)

	def get_context_data(self, **kwargs):
		context = super(ApartmentsListView, self).get_context_data(**kwargs)
		userprofile = get_user_profile(user=self.request.user)
		building_slug = self.kwargs['building_slug']
		building_object = Building.objects.get(slug__iexact=building_slug)
		apartments_in_building = self.model.objects.filter(building=building_object)
		context['building'] = building_object
		context['apartments'] = apartments_in_building
		context['userprofile'] = userprofile
		return context

class ApartmentDetailView(DetailView):
	template_name = "properties/apartment_detail.html"
	model = Apartment
	context_object_name = "apartment"

	def get_object(self, *args, **kwargs):
		building_slug = self.kwargs['building_slug']
		apartment_pk = self.kwargs['apartment_pk']
		building_object = Building.objects.get(slug__iexact=building_slug)
		obj = self.model.objects.get(pk=apartment_pk, building=building_object)
		return obj

	def get_context_data(self, *args, **kwargs):
		context = super(ApartmentDetailView, self).get_context_data(*args, **kwargs)
		userprofile = get_user_profile(user=self.request.user)
		building_slug = self.kwargs['building_slug']
		apartment_pk = self.kwargs['apartment_pk']
		building_object = Building.objects.get(slug__iexact=building_slug)
		apartment_object = self.model.objects.get(pk=apartment_pk, building=building_object)
		context['building'] = building_object
		context['inhabitants'] = apartment_object.inhabitant_set.all()
		context['userprofile'] = userprofile
		try:
			owner = apartment_object.owner_set.all()[0]
		except:
			owner = None
		context['owner'] = owner
		context['visits'] = apartment_object.visit_set.all()
		return context

class ApartmentUpdateView(UpdateView):
	template_name = "properties/edit_apartment.html"
	model = Apartment
	fields = ['name', 'registration_tag', 'area', 'parking_number']

	@method_decorator(permission_required("properties.change_apartment", raise_exception=True))
	def dispatch(self, *args, **kwargs):
		return super(ApartmentUpdateView, self).dispatch(*args, **kwargs)

	def get_object(self, *args, **kwargs):
		building_slug = self.kwargs['building_slug']
		apartment_pk = self.kwargs['apartment_pk']
		building_object = Building.objects.get(slug__iexact=building_slug)
		obj = self.model.objects.get(pk=apartment_pk, building=building_object)
		return obj

	def get_success_url(self, *args, **kwargs):
		building_slug = self.kwargs['building_slug']
		apartment_pk = self.kwargs['apartment_pk']
		return reverse('property_detail', kwargs={'building_slug': building_slug, 'apartment_pk': apartment_pk})

class OwnerUpdateView(UpdateView):
	template_name = "properties/edit_apartment_owner.html"
	model = Owner
	fields = ['name', 'last_name', 'email', 'phone_number', 'address']

	@method_decorator(permission_required("properties.change_owner", raise_exception=True))
	def dispatch(self, *args, **kwargs):
		return super(OwnerUpdateView, self).dispatch(*args, **kwargs)

	def get_object(self, *args, **kwargs):
		building_slug = self.kwargs['building_slug']
		apartment_pk = self.kwargs['apartment_pk']
		building_object = Building.objects.get(slug__iexact=building_slug)
		apartment_object = Apartment.objects.get(pk=apartment_pk, building=building_object)
		obj = apartment_object.owner_set.all()[0]
		return obj

	def get_success_url(self, *args, **kwargs):
		building_slug = self.kwargs['building_slug']
		apartment_pk = self.kwargs['apartment_pk']
		return reverse('property_detail', kwargs={'building_slug': building_slug, 'apartment_pk': apartment_pk})

class InhabitantUpdateView(UpdateView):
	template_name = "properties/edit_apartment_inhabitant.html"
	model = Inhabitant
	fields = ['name', 'last_name', 'email', 'phone_number', 'address']

	@method_decorator(permission_required("properties.change_inhabitant", raise_exception=True))
	def dispatch(self, *args, **kwargs):
		return super(InhabitantUpdateView, self).dispatch(*args, **kwargs)

	def get_object(self, *args, **kwargs):
		building_slug = self.kwargs['building_slug']
		apartment_pk = self.kwargs['apartment_pk']
		inhabitant_pk = self.kwargs['inhabitant_pk']
		building_object = Building.objects.get(slug__iexact=building_slug)
		apartment_object = Apartment.objects.get(pk=apartment_pk, building=building_object)
		obj = apartment_object.inhabitant_set.get(pk=inhabitant_pk)
		return obj

	def get_success_url(self, *args, **kwargs):
		building_slug = self.kwargs['building_slug']
		apartment_pk = self.kwargs['apartment_pk']
		return reverse('property_detail', kwargs={'building_slug': building_slug, 'apartment_pk': apartment_pk})

class VisitCreateView(CreateView):
	model = Visit
	template_name = "properties/create_visit.html"
	fields = ['visitor_name', 'visitor_lastname', 'visitor_identity']

	@method_decorator(permission_required("properties.add_visit", raise_exception=True))
	def dispatch(self, *args, **kwargs):
		return super(VisitCreateView, self).dispatch(*args, **kwargs)

	def get_context_data(self, **kwargs):
		context = super(VisitCreateView, self).get_context_data(**kwargs)
		userprofile = get_user_profile(user=self.request.user)
		building_slug = self.kwargs['building_slug']
		building_object = Building.objects.get(slug__iexact=building_slug)
		context['building'] = building_object
		context['userprofile'] = userprofile
		return context

	def get_success_url(self, *args, **kwargs):
		building_slug = self.kwargs['building_slug']
		apto_pk = self.kwargs['apartment_pk']
		return reverse('property_detail', kwargs={
			'building_slug': building_slug,
			'apartment_pk': apto_pk
		})

	def form_valid(self, form, *args, **kwargs):
		building_slug = self.kwargs['building_slug']
		apto_pk = self.kwargs['apartment_pk']
		building_obj = Building.objects.get(slug__iexact=building_slug)
		apto_obj = Apartment.objects.get(pk=apto_pk, building=building_obj)
		form.instance.apartment = apto_obj
		form.instance.visit_date = timezone.now()
		return super(VisitCreateView, self).form_valid(form)


#FUNCTIONS TO IMPORT AND EXPORT PROPERTIES DATA WITH DJANGO-IMPORT-EXPORT

class ApartmentResource(resources.ModelResource):

    def before_import(self, dataset, dry_run=True, **kwargs):
        """
        Make standard corrections to the dataset before displaying to user
        """
        building=kwargs['building']
        dataset.append_col([None for row in range(len(dataset))], header='id')
        dataset.append_col([building.id for row in range(len(dataset))], header='building')

    class Meta:
        model = Apartment
        fields = ('id', 'name', 'area', 'registration_tag', 'building', 'parking_number', 'coefficient')


class ApartmentExport(View):

    def get(self, *args, **kwargs ):
        dataset = ApartmentResource().export()
        response = HttpResponse(dataset.csv, content_type="csv")
        response['Content-Disposition'] = 'attachment; filename=filename.csv'
        return response


class ApartmentImport(View):
    model = Apartment
    from_encoding = "utf-8"

    #: import / export formats
    DEFAULT_FORMATS = (
        base_formats.CSV,
        base_formats.XLS,
        base_formats.TSV,
        base_formats.ODS,
        base_formats.JSON,
        base_formats.YAML,
        base_formats.HTML,
    )
    formats = DEFAULT_FORMATS
    #: template for import view
    import_template_name = 'properties/import.html'
    resource_class = ApartmentResource

    def get_import_formats(self):
        """
        Returns available import formats.
        """
        return [f for f in self.formats if f().can_import()]

    def get_resource_class(self):
        if not self.resource_class:
            return modelresource_factory(self.model)
        else:
            return self.resource_class

    def get_import_resource_class(self):
        """
        Returns ResourceClass to use for import.
        """
        return self.get_resource_class()

    def get(self, *args, **kwargs ):
        '''
        Perform a dry_run of the import to make sure the import will not
        result in errors.  If there where no error, save the user
        uploaded file to a local temp file that will be used by
        'process_import' for the actual import.
        '''
        resource = self.get_import_resource_class()()
        building_slug = self.kwargs['building_slug']
        building_object = get_object_or_404(Building, slug__iexact=building_slug)

        context = {}

hood/templates/properties/create_visit.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% block leftbar %}
            <div class="left side-menu">
                <div class="sidebar-inner slimscrollleft">
                    <div class="user-details">
                        <div class="user-info">
                            <div>
                                <span aria-expanded="false">
                                    Edificio {{building.name}}
                                </span>
                             </div>
                              {% if userprofile.is_administrator %}
                        <p class="text-muted m-0">Administrador</p>
                              {% elif userprofile.is_watchman %}
                              <p class="text-muted m-0">Celador</p>
                              {% else %}
                              {% endif %}
                    </div>
                </div>
                <div id="sidebar-menu">
                    <ul>
                              {% if perms.properties %}
                              <li>
                                   <a href="{% url "properties" building.slug %}" class="waves-effect active">
                                        <i class="md md-home"></i>
                                        <span>Copropiedad</span>
                                   </a>
                              </li>
                              {% else %}
                              {% endif %}
                              {% if perms.wallet %}
                        <li>
                            <a href="{% url "wallet" building.slug %}" class="waves-effect">
                                <i class="md md-account-balance-wallet"></i>
                                <span>Cartera</span>
                                <span class="pull-right">
                                    <i class="md md-add"></i>
                                </span>
                            </a>
                        </li>
                              {% else %}
                              {% endif %}
                              {% if perms.movements %}
                        <li>
                            <a href="{% url "cashflow" building.slug %}" class="waves-effect">
                                <i class="md md-attach-money"></i>
                                <span>Caja</span>
                            </a>
                        </li>
                              {% else %}
                              {% endif %}
                              {% if perms.emails %}
                        <li>
                            <a href="{% url "emails" building.slug %}" class="waves-effect">
                                <i class="md md-email"></i>
                                <span>Emails</span>
                            </a>
                        </li>
                              {% else %}
                              {% endif %}
                              {% if perms.complaints %}
                                <li>
                                  <a href="{% url "complaints" building.slug %}" class="waves-effect">
                                    <i class="md md-announcement"></i> 
                                    <span>Quejas</span> 
                                    <span class="pull-right">
                                    <i class="md md-add"></i>
                                    </span>
                                  </a>  
                                   </li>
                              {% else %}
                              {% endif %}
                         {% if perms.meetns %}
                         <li>
                            <a href="{% url "meetings" building.slug %}" class="waves-effect">
                                <i class="md md-invert-colors-on"></i>
                                <span>Asambleas/Reuniones</span>
                                <span class="pull-right">
                                    <i class="md md-add"></i>
                                </span>
                            </a>
                         </li>
                         {% else %}
                         {% endif %}
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="clearfix"></div>
               </div>
          </div>
          {% endblock %}
        {% block content %}
            <div class="content-page">
                <div class="content">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-12">
                                <h4 class="pull-left page-title">General elements</h4>
                                <ol class="breadcrumb pull-right">
                                    <li>
                                        <a href="#">Moltran</a>
                                    </li>
                                    <li>
                                        <a href="#">Forms</a>
                                    </li>
                                    <li class="active">General elements</li>
                                </ol>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <h3 class="panel-title">Crear visita</h3>
                                    </div>
                                    <div class="panel-body">
                                        <form class="form-horizontal" role="form" method="POST" action="">
                                        {% csrf_token %}
                                            <div class="form-group">
                                                <label class="col-md-2 control-label">Nombre</label>
                                                <div class="col-md-6">
                                                    <input id="id_visitor_name" maxlength="100" name="visitor_name" type="text"
                                                    class="form-control" placeholder="Nombre">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-2 control-label">Apellido</label>
                                                <div class="col-md-6">
                                                    <input id="id_visitor_lastname" maxlength="100" name="visitor_lastname" type="text" class="form-control" placeholder="Apellido">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-2 control-label">Identidad</label>
                                                <div class="col-md-6">
                                                    <input id="id_visitor_identity" maxlength="100" name="visitor_identity" type="text" class="form-control" placeholder="Número de identidad">
                                                </div>
                                            </div>
                                            <div class="form-group m-b-0">
                                                <div class="col-sm-offset-3 col-sm-9">
                                                    <button type="submit" class="btn btn-info waves-effect waves-light">Guardar</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
        {% endblock %}